In [8]:
from datetime import date
from datetime import datetime

In [22]:
#Transactions

class Transaction:
    type = None          #debit or credit
    amount = None        #amount of transaction
    comments = None      #additional comments
    date = None          #date of transaction
    acc = None           #accont number 
    bank = None          #bank

    def addTransaction(myself,type,comments,amount,acc,bank,date=None):
        myself.type = type
        myself.amount = amount
        myself.comments = comments
        myself.acc = acc
        myself.bank = bank
        if date!=None:
          myself.date = date
        else:
          myself.date = date.today().strftime("%d/%m/%Y")
    

    def printTransaction(self):
        print(">>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
        print("Type: "+self.type)
        print("amount: "+str(self.amount))
        print("comments: "+self.comments)
        print("date: "+self.date)
        print("acc: "+self.acc)
        print("bank: "+self.bank)
        print(">>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n\n\n")

In [41]:
#Month
class Month:
    month = None
    year = None
    allTransactions = []
    totalTransactions = None
    
    def addTransactionToMonth(self,transaction):
        self.allTransactions.append(transaction)
        #sorting the list of transaction according to date
        self.allTransactions.sort(key=lambda x: datetime.strptime(x.date, "%d/%m/%Y"), reverse=False)
    def printAllMonthTransactions(self):
        for i in self.allTransactions:
            print("\n------------------")
            i.printTransaction()
            print("------------------\n")

In [ ]:

#testing Month

temp = [] 

temp1 = Transaction()
temp2 = Transaction()
temp3 = Transaction()
temp4 = Transaction()
temp5 = Transaction()
temp1.addTransaction("Debit","atm transaction for fee1",1050,"112345678890","meezan1",'5/08/2022')
temp2.addTransaction("credit","atm transaction for fee2",1050,"112345678890","meezan2",'3/08/2022')
temp3.addTransaction("Debit","atm transaction for fee3",1050,"112345678890","meezan3",'4/08/2022')
temp4.addTransaction("credit","atm transaction for fee4",1050,"112345678890","meezan4",'2/08/2022')
temp5.addTransaction("Debit","atm transaction for fee5",1050,"112345678890","meezan5",'3/08/2022')

temp.append(temp1)
temp.append(temp2)
temp.append(temp3)
temp.append(temp4)
temp.append(temp5)

month = Month()
month.addTransactionToMonth(temp1)
month.addTransactionToMonth(temp2)
month.addTransactionToMonth(temp3)
month.addTransactionToMonth(temp4)
month.addTransactionToMonth(temp5)
month.printAllMonthTransactions()

In [43]:
#sort transactions by date

temp = [] 

temp1 = Transaction()
temp2 = Transaction()
temp3 = Transaction()
temp4 = Transaction()
temp5 = Transaction()
temp1.addTransaction("Debit","atm transaction for fee1",1050,"112345678890","meezan1",'5/07/2022')
temp2.addTransaction("credit","atm transaction for fee2",1050,"112345678890","meezan2",'3/08/2021')
temp3.addTransaction("Debit","atm transaction for fee3",1050,"112345678890","meezan3",'4/08/2022')
temp4.addTransaction("credit","atm transaction for fee4",1050,"112345678890","meezan4",'2/08/2022')
temp5.addTransaction("Debit","atm transaction for fee5",1050,"112345678890","meezan5",'3/08/2022')

temp.append(temp1)
temp.append(temp2)
temp.append(temp3)
temp.append(temp4)
temp.append(temp5)


for i in temp:
    i.printTransaction()
    print("------------------\n\n")

print("\n\n\n-----------AFTER SORTING---------------\n")
temp.sort(key=lambda x: datetime.strptime(x.date, "%d/%m/%Y"), reverse=False)
for i in temp:
    i.printTransaction()
    print("------------------\n\n")

>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: Debit
amount: 1050
comments: atm transaction for fee1
date: 5/07/2022
acc: 112345678890
bank: meezan1
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: credit
amount: 1050
comments: atm transaction for fee2
date: 3/08/2021
acc: 112345678890
bank: meezan2
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: Debit
amount: 1050
comments: atm transaction for fee3
date: 4/08/2022
acc: 112345678890
bank: meezan3
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: credit
amount: 1050
comments: atm transaction for fee4
date: 2/08/2022
acc: 112345678890
bank: meezan4
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: Debit
amount: 1050
comments: atm transaction for fee5
date: 3/08/2022
acc: 112345678890
bank: meezan5
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------





-----------AFTER SORTING---------------

>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: credit
amount: 1050
comments: atm transaction for fee2
date: 3/08/2021
acc: 112345678890
bank: meezan2
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: Debit
amount: 1050
comments: atm transaction for fee1
date: 5/07/2022
acc: 112345678890
bank: meezan1
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: credit
amount: 1050
comments: atm transaction for fee4
date: 2/08/2022
acc: 112345678890
bank: meezan4
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: Debit
amount: 1050
comments: atm transaction for fee5
date: 3/08/2022
acc: 112345678890
bank: meezan5
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------


>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Type: Debit
amount: 1050
comments: atm transaction for fee3
date: 4/08/2022
acc: 112345678890
bank: meezan3
>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



------------------